"""populate user skill skill_rating user_skill_rating lesson

Revision ID: 1541c1c7d7f1
Revises: 57454267e007
Create Date: 2024-11-05 09:34:46.405696

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1541c1c7d7f1'
down_revision: Union[str, None] = '57454267e007'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
