"""populate user skill skill_rating user_skill_rating lesson

Revision ID: 4d3beb7698da
Revises: 2998ed42b25d
Create Date: 2024-11-05 08:37:52.417524

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d3beb7698da'
down_revision: Union[str, None] = '2998ed42b25d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
